src/java/com/goaml/beans/CreateReportBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.goaml.beans;

import com.goaml.dao.CreateReportDao;
import com.goaml.dao.GeneralData;
import com.goaml.model.FilesHis;
import com.goaml.model.FtFirst;
import com.goaml.model.ReportedTransactions;
import com.goaml.model.TellerTrans;
import com.goaml.utils.HandelSession;
import com.goaml.utils.JsfUtil;
import com.goaml.utils.XmlUtils;
import com.goaml.xml.Address;
import com.goaml.xml.Location;
import com.goaml.xml.ReportingPerson;
import com.goaml.xml.Transaction;
import com.goaml.xml.addresses;
import com.goaml.xml.from_person;
import com.goaml.xml.identification;
import com.goaml.xml.phone;
import com.goaml.xml.phones;
import com.goaml.xml.report;
import com.goaml.xml.report_indicators;
import com.goaml.xml.signatory;
import com.goaml.xml.t_from;
import com.goaml.xml.t_from_my_client;
import com.goaml.xml.t_person;
import com.goaml.xml.t_to_my_client;
import com.goaml.xml.to_account;
import java.io.File;
import java.io.IOException;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import org.apache.commons.io.FileUtils;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.event.SelectEvent;
import org.primefaces.model.UploadedFile;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;

/**
 *
 * @author CODO
 */
@ManagedBean(name = "ReportBean")
@ViewScoped
public class CreateReportBean {

    /**
     * Creates a new instance of CreateReportBean
     */
    CreateReportDao reportDao;
    UsersBean user = null;
    FilesHis fh;
    private String repId;
    private String savePath;
    ReportedTransactions rt;
    GeneralData gd;
    String xmlOutput;
    private UploadedFile fileName;
    String tempPath;
    String uploadedFileName;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH.mm.ss");
    List<String> attatchemnts;
    private FtFirst selecttedCase;
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("resources/messages");
    XmlUtils xmlUtils;

    public CreateReportBean() {
        reportDao = new CreateReportDao();
        HandelSession session = new HandelSession();
        user = (UsersBean) session.getAttribute("userBean");
//        rt = new ReportedTransactions();
        gd = new GeneralData();
        FtFirst selecttedCase = new FtFirst();

        xmlUtils = new XmlUtils();
    }

    private String transNumber;
    private String cusNumber;
    private String action;
    private String reason;
    private List<FtFirst> FirstLS = new ArrayList<FtFirst>();
    private List<TellerTrans> tellerTransList = new ArrayList<TellerTrans>();
    FtFirst newTrans;
    TellerTrans tellerTrans;

    public void addToTransList(ActionEvent event) throws IOException {
        newTrans = new FtFirst();
        tellerTrans = new TellerTrans();
        attatchemnts = new ArrayList<>();
        attatchemnts.add(tempPath);
     
        String transactionType = transNumber.substring(0, 1);
        if (transactionType.equalsIgnoreCase("FT")) {
            newTrans = reportDao.getNewTrans(transNumber, cusNumber);
            if (newTrans == null) {
                JsfUtil.addErrorMessage(bundle.getString("SorryNoTrans"));
            }
            FirstLS.add(newTrans);
            transNumber = null;
            cusNumber = null;
        } else if (transactionType.equalsIgnoreCase("TT")) {
            tellerTrans = reportDao.getTellerTrans(transNumber, cusNumber);
            if (newTrans == null) {
                JsfUtil.addErrorMessage(bundle.getString("SorryNoTrans"));
            }
            
            
            tellerTransList.add(tellerTrans);
            transNumber = null;
            cusNumber = null;
        }

//        action = null;
//        reason = null;
    }

    public void onRowSelect(SelectEvent event) {
        System.out.println("Hhhhhhhhhhhhhh");
        selecttedCase = (FtFirst) event.getObject();

    }

    public void removeTrans() {
        FirstLS.remove(selecttedCase);
        System.out.println("transa Removed:::::");
    }

    public List<FtFirst> getFirstLS() {

        return FirstLS;
    }

    public void setFirstLS(List<FtFirst> FirstLS) {
        this.FirstLS = FirstLS;
    }

    public String getTransNumber() {
        return transNumber;
    }

    public void setTransNumber(String transNumber) {
        this.transNumber = transNumber;
    }

    public String getCusNumber() {
        return cusNumber;
    }

    public void setCusNumber(String cusNumber) {
        this.cusNumber = cusNumber;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public void handleFileUpload(FileUploadEvent event) {
        FacesMessage msg = new FacesMessage("Success! ", event.getFile().getFileName() + " is uploaded.");
        uploadedFileName = event.getFile().getFileName();
        FacesContext.getCurrentInstance().addMessage(null, msg);
        try {
            tempPath = gd.copyFile(event.getFile().getFileName(), event.getFile().getInputstream(), gd.getSubRepPath("XMLOutput"));

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void scenario3() throws IOException {
        String num = "100017";
        repId = num.concat(JsfUtil.generatePIN());
        fh = new FilesHis();
        xmlOutput = gd.getSubRepPath("XMLOutput") + repId;

    }

    public void getData() throws IOException {
        String num = "100017";
        repId = num.concat(JsfUtil.generatePIN());
        fh = new FilesHis();
        xmlOutput = gd.getSubRepPath("XMLOutput") + repId;
        System.out.println("Medooooooooooooooo");
        List<FtFirst> trans = FirstLS;
        List<ReportedTransactions> reList = new ArrayList<>();
        phones phoness = new phones();
        Address a = new Address();
        addresses add = new addresses();
//        Location location = new Location();
        phone phone = new phone();
        List<Transaction> tranList = new ArrayList<>();
        List<Address> address = new ArrayList<>();
        List<phone> phoneLis = new ArrayList<>();
        List<addresses> addressList = new ArrayList<>();
        List<phones> phonesList = new ArrayList<>();
        List<Location> locationList = new ArrayList<>();
        List<report_indicators> report_indicators = new ArrayList<>();
        Transaction t = null;
//        List<FtFirst> trans = FirstLS;
        System.out.println("ListSizeeee::::  " + trans.size());
//        Readxml(FirstLS);

        /////////////Report Header/////////////
        report r = xmlUtils.createRepHeader(repId, reason, action, "STR");
        ReportingPerson reportingPerson = new ReportingPerson();
        //////phoness///////
        phone.setTph_contact_type("P");
        phone.setTph_communication_type("M");
        phone.setTph_number(user.getUsers().getPhone());
        phoneLis.add(phone);
        phoness.setPhone(phoneLis);
        phonesList.add(phoness);
        ///////addressList////////
        a.setAddress_type("B");
        a.setAddress(user.getUsers().getAddress());
        a.setCity("Jiza");
        a.setCountry_code("EG");
        a.setState("Cairo");
        a.setAddress(user.getUsers().getBranch());
        address.add(a);
        add.setAddress(address);
        addressList.add(add);
        ///////////Location/////////////
        String Address_type = "B";
        String Address = "وسط البلد";
        String city = "Cairo";
        String country_code = "EG";
        String state = user.getUsers().getBranch();
        Location location = xmlUtils.createLocation(Address_type, Address, city, country_code, state);
//        location.setAddress_type("B");
//        location.setAddress("وسط البلد");
//        location.setCity("Cairo");
//        location.setCountry_code("EG");
//        location.setState("القاهرة");
        locationList.add(location);
        r.setLocation(locationList);
        //////////reportingPerson///////
        reportingPerson.setAddresses(addressList);
        reportingPerson.setGender(user.getUsers().getGender().substring(0, 1));
        reportingPerson.setTitle(user.getUsers().getTitle());
        reportingPerson.setFirst_name(user.getUsers().getFirstName());
        reportingPerson.setLast_name(user.getUsers().getLastName());
//        String year=user.getUsers().getBirthDate().substring(0, 4);
//        String month=user.getUsers().getBirthDate().substring(5, 6);
//        String day=user.getUsers().getBirthDate().substring(7, 8);
        String formattedDate = xmlUtils.formatDate(user.getUsers().getBirthDate());
        reportingPerson.setBirthdate(formattedDate);

        reportingPerson.setSsn(user.getUsers().getNationalId());
        reportingPerson.setAddresses(addressList);
        reportingPerson.setPhones(phonesList);
        reportingPerson.setEmail(user.getUsers().getEmail());
        reportingPerson.setOccupation(user.getUsers().getOccupation());
        ////////Indicators//////////
        report_indicators indicator = new report_indicators();
        List<String> indicators = new ArrayList<>();
        indicators.add("CC");
        indicators.add("CIUR");
        indicator.setIndicator(indicators);

src/java/com/goaml/beans/CreateUsersBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.goaml.beans;

import com.goaml.dao.GeneralData;
import com.goaml.dao.ModifyUsersDao;
import com.goaml.model.Users;
import com.goaml.utils.JsfUtil;
import java.math.BigDecimal;
import java.util.TreeMap;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;

/**
 *
 * @author Mahmoud
 */
@ManagedBean(name = "CreateUsrBean")
@ViewScoped
public class CreateUsersBean {

    private String firstName;
    private String middleName;
    private String title;
    private String userName;
    private String gender;
    private String nid;
    private String phone;
    private String email;
    private String role;

    private TreeMap rolesMap;
    GeneralData gd;
    private String selectedRole;
    ModifyUsersDao dao;
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("resources/messages");

    public CreateUsersBean() {
        gd = new GeneralData();
        dao = new ModifyUsersDao();
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getMiddleName() {
        return middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getNid() {
        return nid;
    }

    public void setNid(String nid) {
        this.nid = nid;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void createUser(ActionEvent event) {

        Users u = new Users();
        u.setUsername(userName);
        u.setGender(gender);
        u.setTitle(title);
        u.setRoleId(new BigDecimal(selectedRole));
        u.setFirstName(firstName);
        u.setMidlleName(middleName);
        u.setNationalId(nid);
        u.setPhone(phone);
        u.setEmail(email);
        try {
            dao.saveUser(u);
            FacesMessage msg = new FacesMessage("تم انشاء المستخدم");
            FacesContext.getCurrentInstance().addMessage(null, msg);
        } catch (Exception e) {
            JsfUtil.addErrorMessage(bundle.getString("CreateUserError"));
            e.printStackTrace();
        }

    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public TreeMap getRolesMap() {
        rolesMap = gd.getRolesMap();
        return rolesMap;
    }

    public void setRolesMap(TreeMap rolesMap) {
        this.rolesMap = rolesMap;
    }

    public String getSelectedRole() {
        return selectedRole;
    }

    public void setSelectedRole(String selectedRole) {
        this.selectedRole = selectedRole;
    }

}

src/java/com/goaml/beans/EditSarReport.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.goaml.beans;

import com.goaml.dao.ReturnedRepDao;
import com.goaml.model.ReturnedRepData;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

/**
 *
 * @author Mahmoud
 */
@ManagedBean(name = "EditSar")
@ViewScoped
public class EditSarReport {

    private String paramRepId;
    ReturnedRepDao repDao;
    private ReturnedRepData repData;

    public EditSarReport() {
        HttpServletRequest req = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        paramRepId = req.getParameter("repId");
        System.out.println(":::  " + paramRepId);
        repDao = new ReturnedRepDao();
        repData = repDao.getReturnedReportsData(paramRepId);

    }

    public String getParamRepId() {
        return paramRepId;
    }

    public void setParamRepId(String paramRepId) {
        this.paramRepId = paramRepId;
    }

    public ReturnedRepData getRepData() {
        return repData;
    }

    public void setRepData(ReturnedRepData repData) {
        this.repData = repData;
    }

}

src/java/com/goaml/beans/ReviseFilesBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.goaml.beans;

import com.goaml.dao.ReviseFilesDao;
import com.goaml.model.FilesHis;
import com.goaml.model.UploadedFiles;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;

/**
 *
 * @author Mahmoud
 */
@ManagedBean(name = "reviseFiles")
@ViewScoped

public class ReviseFilesBean {

    private List<UploadedFiles> files = new ArrayList<UploadedFiles>();
    ReviseFilesDao dao;

    public ReviseFilesBean() {
        dao = new ReviseFilesDao();
        files = dao.getUploadedFiles();
    }

    public List<UploadedFiles> getFiles() {

        return files;
    }

    public void setFiles(List<UploadedFiles> files) {
        this.files = files;
    }

    public void postProcessXLS(Object document) {
        HSSFWorkbook wb = (HSSFWorkbook) document;
        HSSFSheet sheet = wb.getSheetAt(0);
        CellStyle style = wb.createCellStyle();
        style.setFillBackgroundColor(IndexedColors.AQUA.getIndex());

        for (Row row : sheet) {
            for (Cell cell : row) {
                cell.setCellValue(cell.getStringCellValue().toUpperCase());
                cell.setCellStyle(style);
            }
        }
    }
}

web/App/EditStrReport.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>#{bundle.EditReport}</title>
    </h:head>
    <h:body>
        <body>
            <ui:composition template=".././Template/common.xhtml">
                <ui:define name="title">Edit STR Report</ui:define>

                <ui:define name="content">
                    <h:form id="mainFrm">
                        <div class="container-fluid main_container">
                            <div class="row">

                                <div class="col-sm-10  col-sm-offset-2">
                                    <div class="row">
                                        <div class="contnent_wrapper col-sm-12">
                                            <h3 class="page_header">#{bundle.EditReport}</h3>
                                            <div class=" content_container col-sm-12  ">
                                                <div class="row line_bottom">
                                                    <div class="col-sm-6">
                                                        <div class="row">
                                                            <div class="col-sm-3">
                                                                <label> #{bundle.TransactionREf}</label>
                                                            </div>

                                                            <div class="col-sm-6">
                                                                <h:form id="trans">
                                                                    <p:inputText   requiredMessage="#{bundle.TransREfRequiredErr}" value="#{ReportBean.transNumber}" id="trans">
                                                                        <p:ajax event="valueChange"  process="@this"/>
                                                                    </p:inputText>
                                                                </h:form>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <!--col-->
                                                    <div class="col-sm-6">
                                                        <div class="row">
                                                            <div class="col-sm-3">
                                                                <label>#{bundle.CustomerNo} </label>
                                                            </div>
                                                            <div class="col-sm-6">
                                                                <h:form id="cusNo">
                                                                    <p:inputText   requiredMessage="#{bundle.TransREfRequiredErr}" value="#{ReportBean.cusNumber}" id="cusNo">
                                                                        <p:ajax event="valueChange"  process="@this"/>
                                                                    </p:inputText>
                                                                </h:form>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <!--col-->
                                                </div>

                                                <div class="row line_bottom">
                                                    <div class="col-sm-6">
                                                        <div class="row">
                                                            <div class="col-sm-3">
                                                                <label> #{bundle.Reason}</label>
                                                            </div>
                                                            <div class="col-sm-6">
                                                                <h:form id="reason">
                                                                    <p:inputTextarea rows="3"  value="#{ReportBean.reason}" id="reason" >
                                                                        <p:ajax event="valueChange"  process="@this"/>
                                                                    </p:inputTextarea>
                                                                </h:form>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <!--col-->
                                                    <div class="col-sm-6">
                                                        <div class="row">
                                                            <div class="col-sm-3">
                                                                <label>#{bundle.Action} </label>
                                                            </div>
                                                            <div class="col-sm-6">
                                                                <h:form id="action">
                                                                    <p:inputTextarea rows="3" value="#{ReportBean.action}" id="action" >
                                                                        <p:ajax event="valueChange"  process="@this"/>
                                                                    </p:inputTextarea>
                                                                </h:form>
                                                            </div>

                                                        </div>

                                                    </div>
                                                    <!--col-->
                                                </div>
                                 
                                 
                                                <div class="row line_bottom">
                                                    <div class="col-sm-6">
                                                        <div class="row">

                                                            <div class="col-sm-6">
                                                                <p:commandButton value="#{bundle.AddTrans}"   update=":mainFrm:form2:cases :mainFrm:action:action :mainFrm:reason:reason :mainFrm:cusNo:cusNo :mainFrm:trans:trans" actionListener="#{ReportBean.addToTransList(event)}" icon="ui-icon-circle-plus"/>
<!--                                                                <p:commandButton value="#{bundle.GetData}"   update=":mainFrm:form2:cases" actionListener="#{ReportBean.getData}"/>-->

                                                                <!--                                                               <p:ajax event="valueChange"  process="@this"/>-->

                                                            </div>
                                                        </div>
                                                    </div>
                                                    <!--col-->
                                                </div>

                                                <!--line_bottom-->
                                                <div class="row line_bottom">
                                                    <div class="col-sm-12">
                                                        <h:form id="form2">
                                                            <p:dataTable id="cases" selection="#{ReportBean.selecttedCase}" selectionMode="single" rowKey="#{cases.FTRECID}"
                                                                         value="#{ReportBean.firstLS}" widgetVar="cases"  var="cases"   emptyMessage="#{bundle.NorecordsFound}" >

                                                                <p:ajax event="rowSelect"  listener="#{ReportBean.onRowSelect}" update="cases" 
                                                                        process="@this"  
                                                                        />
                                                                <p:column headerText="#{bundle.CustomerName}">
                                                                    <h:outputText value="#{cases.CUSCUSNAME}"></h:outputText>
                                                                </p:column>
                                                                <p:column headerText="#{bundle.CustomerNID}">
                                                                    <h:outputText value="#{cases.CUSLEGAL_ID}"></h:outputText>
                                                                </p:column>
                                                                <p:column headerText="#{bundle.CustomerNID}">
                                                                    <h:outputText value="#{cases.CUSADDRES1}"></h:outputText>
                                                                </p:column>
                                                                <p:column headerText="#{bundle.AccountNo}">
                                                                    <h:outputText value="#{cases.ACCACCOUNT_NUMBER}"></h:outputText>
                                                                </p:column>

                                                                <p:column headerText="#{bundle.Currency}">
                                                                    <h:outputText value="#{cases.FTDEBIT_CURRENCY}"></h:outputText>
                                                                </p:column>
                                                                <p:column headerText="#{bundle.TransactionDate}">
                                                                    <h:outputText value="#{cases.FTPROCESSING_DATE}"></h:outputText>
                                                                </p:column>
                                                                <p:column headerText="#{bundle.TransvalueDate}">
                                                                    <h:outputText value="#{cases.FTDEBIT_VALUE_DATE}"></h:outputText>
                                                                </p:column>
                                                                <p:column headerText="#{bundle.TransAmount}">
                                                                    <h:outputText value="#{cases.FTDEBIT_AMOUNT}"></h:outputText>
                                                                </p:column>
                                                                <p:column headerText="#{bundle.TransDescription}">
                                                                    <h:outputText value="#{cases.FTMBSC_NOTE}"></h:outputText>
                                                                </p:column>


                                                            </p:dataTable>

                                                        </h:form>

                                                    </div>
                                                    <!--col-->
                                                </div>
                                                <div class="col-sm-4">
                                                    <p:commandButton  id="createRep"   value="#{bundle.CreateReport}" icon="ui-icon-circle-check"  actionListener="#{ReportBean.getData}"  update=":growl"></p:commandButton>
                                                    <p:commandButton  id="removeTrans"   value="#{bundle.RemoveTransaction}" icon="ui-icon-circle-close"  actionListener="#{ReportBean.removeTrans}"  update=":growl :mainFrm:form2:cases" ></p:commandButton>
                                                    <p:commandButton  id="save"   value="#{bundle.SaveforHold}" icon="ui-icon-disk"   update=":growl :mainFrm:form2:cases" ></p:commandButton>
                                                    <!--line_bottom-->
                                                </div>
                                            </div>
                                            <!--content_container-->
                                        </div>
                                        <!--contnent_wrapper-->
                                    </div>
                                </div>
                                <!--col-->
                            </div>
                            <!--row-->


                        </div>
                        <!--container-->

                    </h:form>

                </ui:define>
            </ui:composition>

        </body>
    </h:body>
</html>

web/App/ReportTest.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
      <h:form id="form" target="_blank">
                <h:outputLabel>Export Report</h:outputLabel>
                <h:selectOneRadio value="#{reportsBean.exportOption}">
                    <f:selectItem itemValue="PDF" itemLabel="PDF"/>
                    <f:selectItem itemValue="HTML" itemLabel="HTML"/>
                    <f:selectItem itemValue="EXCEL" itemLabel="EXCEL"/>
                    <f:selectItem itemValue="RTF" itemLabel="RTF"/>
                </h:selectOneRadio>
                <h:commandButton  action="#{reportsBean.execute}" value="Get Report" />
            </h:form>
    </h:body>
</html>